package ru.eljke.driftguard.demo.api;

import io.swagger.v3.oas.models.media.Schema;
import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Map;

/**
 * Adds domain-specific descriptions to schemas generated from library records.
 */
@SuppressWarnings("rawtypes")
@Configuration
public class OpenApiSchemaConfiguration {
    @Bean
    public OpenApiCustomizer driftGuardSchemaDescriptions() {
        return openApi -> {
            Map<String, Schema> schemas = openApi.getComponents().getSchemas();
            describe(schemas, "DemoRunResult", "Result of a synthetic or live demo scenario.", Map.of(
                    "scenario", "Scenario id used for the run.",
                    "title", "Human-readable scenario title.",
                    "metricPoints", "Number of processed metric points.",
                    "samplePoints", "Metric points shown in the UI chart.",
                    "expectedDrifts", "Expected drift intervals generated by the scenario.",
                    "events", "Representative drift events emitted by DriftGuard.",
                    "quality", "Precision, recall and detection-delay metrics."
            ));
            describe(schemas, "DetectionMetrics", "Quality metrics calculated against expected drift intervals.", Map.of(
                    "events", "Total emitted drift events.",
                    "truePositiveEvents", "Events inside expected drift intervals.",
                    "falsePositiveEvents", "Events outside expected drift intervals.",
                    "expectedDriftIntervals", "Expected drift interval count.",
                    "detectedDriftIntervals", "Expected intervals with at least one event.",
                    "missedDriftIntervals", "Expected intervals without detected events.",
                    "detected", "Whether any expected drift interval was detected.",
                    "firstDetectionDelay", "Delay from first expected drift point to first detection.",
                    "precision", "Share of emitted events that were true positives.",
                    "recall", "Share of expected intervals that were detected."
            ));
            describe(schemas, "DriftEvent", "Alert emitted by a DriftGuard detector.", Map.ofEntries(
                    Map.entry("id", "Stable event id."),
                    Map.entry("key", "Metric stream that produced the alert."),
                    Map.entry("detectedAt", "Timestamp of the detection."),
                    Map.entry("direction", "Detected drift direction."),
                    Map.entry("severity", "Warning or critical severity."),
                    Map.entry("score", "Algorithm-specific drift score."),
                    Map.entry("currentValue", "Current observed value."),
                    Map.entry("baselineValue", "Reference value used for comparison."),
                    Map.entry("detector", "Detector definition name."),
                    Map.entry("algorithm", "Algorithm id."),
                    Map.entry("reason", "Short explanation of the detection.")
            ));
            describe(schemas, "MetricPoint", "Single metric observation consumed by DriftGuard.", Map.of(
                    "key", "Logical metric stream key.",
                    "timestamp", "Observation timestamp.",
                    "value", "Observed numeric value.",
                    "kind", "Metric kind such as duration, rate or size.",
                    "tags", "Low-cardinality labels.",
                    "attributes", "Additional observation attributes."
            ));
            describe(schemas, "MetricKey", "Logical identity of a metric stream.", Map.of(
                    "service", "Service that produced the metric.",
                    "metric", "Metric name.",
                    "instance", "Stream instance id.",
                    "operation", "Operation or endpoint name."
            ));
            describe(schemas, "DriftInterval", "Expected drift interval used by quality evaluation.", Map.of(
                    "start", "First expected drift timestamp.",
                    "end", "Last expected drift timestamp."
            ));
            describe(schemas, "DemoScenarioDescriptor", "Scenario available in the demo product.", Map.of(
                    "id", "Stable scenario id.",
                    "title", "Scenario display title.",
                    "metric", "Primary metric affected by the scenario.",
                    "description", "Scenario behavior summary."
            ));
            describe(schemas, "KafkaDemoStatus", "Current Kafka playback status.", Map.ofEntries(
                    Map.entry("enabled", "Whether Kafka demo endpoints are enabled."),
                    Map.entry("running", "Whether playback is active."),
                    Map.entry("scenario", "Active scenario id."),
                    Map.entry("inputTopic", "Topic receiving metric points."),
                    Map.entry("outputTopic", "Topic receiving drift events."),
                    Map.entry("bootstrapServers", "Kafka bootstrap servers."),
                    Map.entry("producedPoints", "Number of produced metric points."),
                    Map.entry("totalPoints", "Total planned metric points."),
                    Map.entry("producers", "Per-producer playback states."),
                    Map.entry("consumedEvents", "Drift events consumed by the demo UI."),
                    Map.entry("samplePoints", "Recent sample points shown by the UI."),
                    Map.entry("error", "Latest playback error, if any.")
            ));
            describe(schemas, "KafkaProducerStatus", "Playback status for one Kafka producer.", Map.of(
                    "id", "Producer identifier.",
                    "service", "Metric service name.",
                    "metric", "Metric name.",
                    "operation", "Metric operation or endpoint.",
                    "producedPoints", "Number of sent points.",
                    "totalPoints", "Total points in the producer scenario.",
                    "running", "Whether this producer is active."
            ));
            describe(schemas, "ToolLink", "Link to a local observability or API tool.", Map.of(
                    "id", "Tool identifier.",
                    "title", "Display title.",
                    "url", "Tool URL.",
                    "description", "Why the tool is useful in the demo."
            ));
            describe(schemas, "DemoConfigurationView", "Effective detector and Kafka configuration.", Map.of(
                    "aggressiveness", "Active detector sensitivity profile.",
                    "kafka", "Kafka playback configuration.",
                    "detectors", "Active detector definitions."
            ));
            describe(schemas, "AggressivenessView", "Human-readable detector profile description.", Map.of(
                    "level", "Profile label.",
                    "description", "Expected profile behavior."
            ));
            describe(schemas, "KafkaConfigurationView", "Kafka settings used by demo playback.", Map.of(
                    "demoEnabled", "Whether Kafka playback endpoints are enabled.",
                    "bootstrapServers", "Kafka bootstrap servers.",
                    "inputTopic", "Topic receiving metric points.",
                    "outputTopic", "Topic receiving drift events.",
                    "applicationId", "Kafka Streams application id.",
                    "playbackInterval", "Base delay between produced metric points."
            ));
            describe(schemas, "DemoScenarioRequest", "Optional scenario generation overrides.", Map.of(
                    "samples", "Number of generated metric samples.",
                    "baselineValue", "Stable value before drift.",
                    "driftValue", "Value during step, drop or spike drift.",
                    "noiseStdDev", "Noise standard deviation.",
                    "driftStartPercent", "Drift start position as stream percentage.",
                    "spikeLengthPercent", "Spike duration as stream percentage."
            ));
            describe(schemas, "KafkaReplayRequest", "Kafka replay request with scenario and detector options.", Map.of(
                    "scenario", "Synthetic scenario id.",
                    "speed", "Playback speed multiplier.",
                    "resetState", "Whether detector state is reset before replay.",
                    "profile", "Optional detector profile to activate.",
                    "samples", "Number of generated metric samples.",
                    "baselineValue", "Stable value before drift.",
                    "driftValue", "Value during step, drop or spike drift.",
                    "noiseStdDev", "Noise standard deviation.",
                    "driftStartPercent", "Drift start position as stream percentage.",
                    "spikeLengthPercent", "Spike duration as stream percentage."
            ));
            describe(schemas, "DetectorConfigurationView", "Effective UI view of one detector definition.", Map.ofEntries(
                    Map.entry("name", "Detector name."),
                    Map.entry("algorithm", "Algorithm id."),
                    Map.entry("services", "Selected services."),
                    Map.entry("metrics", "Selected metric names."),
                    Map.entry("warningThreshold", "Warning threshold."),
                    Map.entry("criticalThreshold", "Critical threshold."),
                    Map.entry("warningPValue", "Warning p-value."),
                    Map.entry("criticalPValue", "Critical p-value."),
                    Map.entry("warmupSamples", "Samples required before detection starts."),
                    Map.entry("emissionPolicy", "Alert emission policy."),
                    Map.entry("sensitivity", "Active profile and runtime version.")
            ));
            describe(schemas, "EmissionPolicyView", "Policy used to suppress noisy repeated alerts.", Map.of(
                    "minConsecutiveSignals", "Signals required before emitting an alert.",
                    "cooldown", "Minimum delay between repeated alerts."
            ));
        };
    }

    private static void describe(Map<String, Schema> schemas, String name, String description, Map<String, String> properties) {
        Schema schema = schemas.get(name);
        if (schema == null) {
            return;
        }
        schema.setDescription(description);
        Map<String, Schema> schemaProperties = schema.getProperties();
        if (schemaProperties == null) {
            return;
        }
        properties.forEach((property, propertyDescription) -> {
            Schema propertySchema = schemaProperties.get(property);
            if (propertySchema != null) {
                propertySchema.setDescription(propertyDescription);
            }
        });
    }
}
