global:
  scrape_interval: 5s

scrape_configs:
  - job_name: driftguard-demo-docker
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - driftguard-demo:8080

  - job_name: driftguard-demo-local
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081
